import type {
  Requirement,
  Proposal,
  Provider,
  Notification,
  Project,
  Review,
  AdminUser,
  AdminStats,
  ReportedContent,
  SubscriptionStats,
} from "./types"

export const mockRequirements: Requirement[] = [
  {
    id: "1",
    title: "E-commerce Website Development",
    description:
      "Looking for a modern e-commerce platform with payment integration, inventory management, and mobile responsiveness. The site should handle 1000+ products and support multiple payment gateways.",
    category: "Web Development",
    budgetMin: 5000,
    budgetMax: 10000,
    timeline: "3 months",
    status: "open",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    location: "Hyderabad",
    seekerId: "1",
    attachments: ["project-brief.pdf", "wireframes.png"],
  },
  {
    id: "2",
    title: "Mobile App UI/UX Design",
    description:
      "Need a complete UI/UX design for a fitness tracking mobile app. Should include user onboarding, workout tracking, progress analytics, and social features.",
    category: "Design",
    budgetMin: 2000,
    budgetMax: 5000,
    timeline: "6 weeks",
    status: "shortlisted",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-20"),
    seekerId: "1",
  },
  {
    id: "3",
    title: "Digital Marketing Campaign",
    description:
      "Comprehensive digital marketing strategy for B2B SaaS product launch. Includes SEO, content marketing, social media, and paid advertising campaigns.",
    category: "Marketing",
    budgetMin: 1000,
    budgetMax: 3000,
    timeline: "2 months",
    status: "negotiation",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25"),
    seekerId: "1",
  },
]

export const mockProposals: Proposal[] = [
  {
    id: "1",
    requirementId: "1",
    providerId: "p1",
    providerName: "TechCraft Solutions",
    providerCompany: "TechCraft Inc.",
    proposedCost: 8500,
    timeline: "10 weeks",
    workApproach:
      "We will use React/Next.js for the frontend with Node.js backend. The project will be delivered in 4 phases: Planning & Design, Development, Testing, and Deployment.",
    milestones: [
      "Requirements Analysis",
      "UI/UX Design",
      "Frontend Development",
      "Backend Integration",
      "Testing & Launch",
    ],
    status: "pending",
    createdAt: new Date("2024-01-16"),
    rating: 4.9,
    verified: true,
  },
  {
    id: "2",
    requirementId: "1",
    providerId: "p2",
    providerName: "WebDev Pro",
    providerCompany: "WebDev Solutions",
    proposedCost: 7200,
    timeline: "12 weeks",
    workApproach:
      "Using WordPress with WooCommerce for faster development and easier maintenance. Custom theme development with advanced e-commerce features.",
    milestones: ["Setup & Planning", "Theme Development", "E-commerce Integration", "Testing", "Go Live"],
    status: "pending",
    createdAt: new Date("2024-01-17"),
    rating: 4.7,
    verified: true,
  },
  {
    id: "3",
    requirementId: "2",
    providerId: "p3",
    providerName: "Creative Design Studio",
    providerCompany: "Creative Inc.",
    proposedCost: 3500,
    timeline: "5 weeks",
    workApproach:
      "Complete UI/UX design process including user research, wireframing, prototyping, and final designs. Delivered in Figma with design system.",
    milestones: ["User Research", "Wireframes", "UI Design", "Prototyping", "Final Delivery"],
    status: "shortlisted",
    createdAt: new Date("2024-01-12"),
    rating: 4.8,
    verified: true,
  },
]

export const categories = [
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Digital Marketing",
  "Content Writing",
  "SEO Services",
  "Graphic Design",
  "Video Production",
  "Consulting",
  "Data Analysis",
]

export const mockProvider: Provider = {
  id: "p1",
  userId: "2",
  companyName: "TechCraft Solutions",
  description:
    "We are a full-service digital agency specializing in web development, mobile apps, and digital transformation. With over 5 years of experience, we have delivered 100+ successful projects.",
  services: ["Web Development", "Mobile Development", "UI/UX Design", "E-commerce"],
  portfolio: [
    {
      id: "1",
      title: "E-commerce Platform for Fashion Brand",
      description:
        "Built a complete e-commerce solution with inventory management, payment processing, and analytics dashboard.",
      category: "Web Development",
      imageUrl: "/ecommerce-fashion-website.png",
      projectUrl: "https://example-fashion.com",
      completedAt: new Date("2024-01-01"),
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    },
    {
      id: "2",
      title: "Mobile Banking App",
      description:
        "Developed a secure mobile banking application with biometric authentication and real-time transactions.",
      category: "Mobile Development",
      imageUrl: "/mobile-banking-app.png",
      completedAt: new Date("2023-12-15"),
      technologies: ["React Native", "Firebase", "Plaid API"],
    },
    {
      id: "3",
      title: "SaaS Dashboard Design",
      description: "Created a comprehensive dashboard design for a project management SaaS platform.",
      category: "UI/UX Design",
      imageUrl: "/modern-saas-dashboard.png",
      completedAt: new Date("2023-11-20"),
      technologies: ["Figma", "Design System", "Prototyping"],
    },
  ],
  rating: 4.9,
  reviewCount: 127,
  verified: true,
  featured: true,
  subscriptionTier: "standard",
  location: "San Francisco, CA",
  website: "https://techcraft.com",
  foundedYear: 2019,
}

export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "2",
    type: "shortlisted",
    title: "Proposal Shortlisted!",
    message: 'Your proposal for "E-commerce Website Development" has been shortlisted by the client.',
    read: false,
    createdAt: new Date("2024-01-20"),
    relatedId: "1",
  },
  {
    id: "2",
    userId: "2",
    type: "new_requirement",
    title: "New Requirement Match",
    message: 'A new requirement matching your services has been posted: "Mobile App Development"',
    read: false,
    createdAt: new Date("2024-01-19"),
    relatedId: "4",
  },
  {
    id: "3",
    userId: "2",
    type: "revision_requested",
    title: "Revision Requested",
    message: 'Client has requested revisions for your proposal on "Digital Marketing Campaign"',
    read: true,
    createdAt: new Date("2024-01-18"),
    relatedId: "3",
  },
]

export const mockProviderProjects: Project[] = [
  {
    id: "1",
    requirementId: "1",
    proposalId: "1",
    seekerId: "1",
    providerId: "p1",
    status: "active",
    startDate: new Date("2024-01-15"),
    budget: 8500,
    milestones: [
      {
        id: "1",
        title: "Requirements Analysis",
        description: "Gather and analyze project requirements",
        dueDate: new Date("2024-01-25"),
        completed: true,
        completedAt: new Date("2024-01-24"),
      },
      {
        id: "2",
        title: "UI/UX Design",
        description: "Create wireframes and design mockups",
        dueDate: new Date("2024-02-10"),
        completed: false,
      },
      {
        id: "3",
        title: "Frontend Development",
        description: "Develop the user interface",
        dueDate: new Date("2024-03-01"),
        completed: false,
      },
    ],
  },
]

export const mockProviderReviews: Review[] = [
  {
    id: "1",
    projectId: "1",
    seekerId: "1",
    providerId: "p1",
    rating: 5,
    qualityRating: 5,
    costRating: 4,
    timelinessRating: 5,
    comment:
      "Excellent work! The team delivered exactly what we needed on time and within budget. The communication was outstanding throughout the project, and they went above and beyond to ensure our satisfaction. Highly recommended for any web development needs!",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    projectId: "2",
    seekerId: "2",
    providerId: "p1",
    rating: 4,
    qualityRating: 4,
    costRating: 5,
    timelinessRating: 4,
    comment:
      "Great communication and quality work. There were minor delays due to some scope changes we requested, but the team handled everything professionally. The final product exceeded our expectations and the pricing was very competitive.",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "3",
    projectId: "3",
    seekerId: "3",
    providerId: "p1",
    rating: 5,
    qualityRating: 5,
    costRating: 5,
    timelinessRating: 5,
    comment:
      "Outstanding service from start to finish! The team was incredibly professional, delivered on time, and the quality of work was exceptional. They understood our requirements perfectly and provided valuable suggestions that improved the final outcome.",
    createdAt: new Date("2023-12-28"),
  },
  {
    id: "4",
    projectId: "4",
    seekerId: "4",
    providerId: "p1",
    rating: 3,
    qualityRating: 3,
    costRating: 4,
    timelinessRating: 2,
    comment:
      "The work quality was decent, but there were significant delays that impacted our launch timeline. Communication could have been better, especially regarding project updates. The final deliverable met our basic requirements but lacked some of the polish we expected.",
    createdAt: new Date("2023-12-15"),
  },
  {
    id: "5",
    projectId: "5",
    seekerId: "5",
    providerId: "p1",
    rating: 4,
    qualityRating: 4,
    costRating: 3,
    timelinessRating: 5,
    comment:
      "Solid work delivered ahead of schedule. The team was responsive and made revisions quickly when requested. While the pricing was a bit higher than expected, the quality and speed of delivery made it worthwhile. Would consider working with them again.",
    createdAt: new Date("2023-12-01"),
  },
]

export const mockAdminUsers: AdminUser[] = [
  {
    id: "1",
    name: "John Doe",
    email: "seeker@example.com",
    role: "client",
    status: "active",
    createdAt: new Date("2024-01-01"),
    lastLogin: new Date("2024-01-20"),
    companyName: "Tech Corp",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "provider@example.com",
    role: "agency",
    status: "active",
    createdAt: new Date("2024-01-02"),
    lastLogin: new Date("2024-01-19"),
    companyName: "Design Studio",
    subscriptionTier: "standard",
  },
  {
    id: "3",
    name: "Bob Wilson",
    email: "bob@example.com",
    role: "agency",
    status: "pending",
    createdAt: new Date("2024-01-18"),
    companyName: "Dev Solutions",
    subscriptionTier: "basic",
  },
  {
    id: "4",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "client",
    status: "suspended",
    createdAt: new Date("2024-01-10"),
    lastLogin: new Date("2024-01-15"),
    companyName: "Marketing Inc",
  },
]

export const mockAdminStats: AdminStats = {
  totalUsers: 1247,
  totalProviders: 423,
  totalSeekers: 824,
  totalRequirements: 156,
  totalProposals: 892,
  totalProjects: 234,
  totalRevenue: 45600,
  monthlyGrowth: 12.5,
}

export const mockReportedContent: ReportedContent[] = [
  {
    id: "1",
    type: "review",
    contentId: "1",
    reportedBy: "user123",
    reason: "Inappropriate content",
    description: "This review contains offensive language and false accusations.",
    status: "pending",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    type: "proposal",
    contentId: "2",
    reportedBy: "user456",
    reason: "Spam",
    description: "This proposal appears to be spam with unrealistic pricing.",
    status: "pending",
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "3",
    type: "user",
    contentId: "p2",
    reportedBy: "user789",
    reason: "Fraudulent activity",
    description: "This agency has been using fake credentials and portfolio items.",
    status: "resolved",
    createdAt: new Date("2024-01-15"),
    resolvedAt: new Date("2024-01-18"),
    resolvedBy: "admin1",
  },
]

export const mockSubscriptionStats: SubscriptionStats = {
  basic: 245,
  standard: 156,
  premium: 22,
  totalRevenue: 28400,
  monthlyRecurring: 15600,
  totalSubscriptions: 423,
}

export const mockProviders: Provider[] = [
  mockProvider,
  {
    id: "p2",
    userId: "3",
    companyName: "WebDev Solutions",
    description:
      "Specialized in WordPress and e-commerce development. We create fast, secure, and scalable websites for businesses of all sizes.",
    services: ["Web Development", "E-commerce", "WordPress", "SEO"],
    portfolio: [
      {
        id: "4",
        title: "Restaurant Chain Website",
        description: "Multi-location restaurant website with online ordering and reservation system.",
        category: "Web Development",
        imageUrl: "/restaurant-website.png",
        completedAt: new Date("2023-12-01"),
        technologies: ["WordPress", "WooCommerce", "Custom Theme"],
      },
    ],
    rating: 4.7,
    reviewCount: 89,
    verified: true,
    featured: false,
    subscriptionTier: "basic",
    location: "Austin, TX",
    website: "https://webdevsolutions.com",
    foundedYear: 2020,
    hourlyRate: 75,
  },
  {
    id: "p3",
    userId: "4",
    companyName: "Creative Design Studio",
    description:
      "Award-winning design agency focused on creating beautiful and functional user experiences for web and mobile applications.",
    services: ["UI/UX Design", "Graphic Design", "Branding", "Prototyping"],
    portfolio: [
      {
        id: "5",
        title: "Fitness App Design",
        description: "Complete UI/UX design for a fitness tracking mobile application.",
        category: "UI/UX Design",
        imageUrl: "/fitness-app-design.png",
        completedAt: new Date("2023-11-15"),
        technologies: ["Figma", "Adobe Creative Suite", "Principle"],
      },
    ],
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    featured: true,
    subscriptionTier: "premium",
    location: "New York, NY",
    website: "https://creativedesignstudio.com",
    foundedYear: 2018,
    hourlyRate: 120,
  },
  {
    id: "p4",
    userId: "5",
    companyName: "Digital Marketing Pro",
    description:
      "Full-service digital marketing agency helping businesses grow their online presence through strategic campaigns and data-driven insights.",
    services: ["Digital Marketing", "SEO", "Content Marketing", "Social Media"],
    portfolio: [
      {
        id: "6",
        title: "SaaS Marketing Campaign",
        description: "Comprehensive digital marketing strategy that increased leads by 300%.",
        category: "Digital Marketing",
        imageUrl: "/marketing-campaign.png",
        completedAt: new Date("2023-10-30"),
        technologies: ["Google Ads", "Facebook Ads", "Analytics", "HubSpot"],
      },
    ],
    rating: 4.6,
    reviewCount: 73,
    verified: true,
    featured: false,
    subscriptionTier: "standard",
    location: "Los Angeles, CA",
    website: "https://digitalmarketingpro.com",
    foundedYear: 2021,
    hourlyRate: 95,
  },
]
